# GitLab CI CD Configuration

stages:
  - lint
  - release
  - deploy

default:
  image: node:20
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

# -----------------
# Lint Stage
# -----------------
check:
  stage: lint
  script:
    - npm ci
    - npm run lint
    - npm run test:coverage
    - npm run build
  coverage: '/Lines\s*:\s*(\d+(?:\.\d+)?%)/'
  artifacts:
    expire_in: 1 week
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
      - dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# -----------------
# Release Stage
# -----------------
publish:
  stage: release
  before_script:
    - echo "@stball:registry=https://gitlab.com/api/v4/projects/35990217/packages/npm/" > .npmrc
    - echo "//gitlab.com/api/v4/projects/35990217/packages/npm/:_authToken=$NPM_TOKEN" >> .npmrc
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git remote add gitlab_origin "${CI_REPOSITORY_URL}"
    - npm config list
  script:
    - npm ci
    - npm run build
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# -----------------
# Deploy Stage (GitLab Pages)
# -----------------
pages:
  stage: deploy
  script:
    - npm ci
    - npm run build:demo
    - mv dist-demo public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
